version: 0.0
os: linux
files:
    - source: /
      destination: /var/www/wordpress/


 hooks:
    Applicationstop:
          - location: /script/stop_script.sh
            timeout: 300
            runas: root

    Applicationstart:
          - location: /script/start_script.sh
            timeout: 300
            runas: root
